---
motd_system: Home
motd_sys_env: Core

cis_level_1_exclusions: ['1.2.3','1.3.1','1.8','2.2.7','3.4.1','3.4.2','3.4.3','3.4.4','3.4.5','5.2.8','5.3.2']
cis_level_2_exclusions: ['6.1.1']
  # 1.2.3   - GPG checking
  # 1.3.1   - 'aide --init' on EL8 hangs
  # 1.8     - Yum update *
  # 2.2.7   - Removes ipa-client as a dependency of rpcbind/nfs-utils.
  # 3.4.2-5 - hosts.allow and hosts.deny not configured
  # 5.2.8   - Disable root ssh
  # 5.3.2   - PAM config
  # 6.1.1.  - Audit Sytem File Permissions
cis_chrony_servers: |+
  server ntp1.core.home.gatwards.org iburst
  server ntp2.core.home.gatwards.org iburst
  server ntp3.core.home.gatwards.org iburst
cis_ntp_clients: "{{ cis_chrony_servers }}"
cis_rsyslog_remote_loghost_address: "syslog.core.home.gatwards.org"
cis_local_login_warning_banner: |+
  ###############################################################
  #  All connections to this system are monitored and recorded  #
  #  Disconnect IMMEDIATELY if you are not an authorized user!  #
  ###############################################################
cis_remote_login_warning_banner: "{{ cis_local_login_warning_banner }}"
cis_sshd_client_alive_interval: 82400

generic_dns_servers:
- 172.22.1.3
- 172.22.1.5
generic_ldap_servers:
- ipa01.ipa.home.gatwards.org
- ipa02.ipa.home.gatwards.org
generic_ldap_basedn: dc=ipa,dc=home,dc=gatwards,dc=org

node_exporter_version: 1.1.2
node_exporter_textfile_deploy: true
node_exporter_enabled_collectors:
- diskstats
- filesystem:
    ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
    ignored-fs-types: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
- logind
- mountstats
- netstat
- systemd
- textfile:
    directory: "{{ node_exporter_textfile_dir }}"
node_exporter_disabled_collectors:
- infiniband
- uname
- xfs

# Common SSL parameters
tls_cafile: /etc/pki/ca-trust/source/anchors/GatwardIT-IPA.pem

# InfluxDB is used by multiple groups, common params defined here
influxdb_host: influxdb.core.home.gatwards.org

# MQTT broker is used by multiple groups, common params defined here
mqtt_broker_fqdn: mqtt.core.home.gatwards.org

# Location parameters used in multple groups
latitude: "{{ vault_latitude }}"
longitude: "{{ vault_longitude }}"
altitude: '698'
