---
motd_role: IPA Server
ipa_server_realm: IPA.HOME.GATWARDS.ORG
cis_level_1_exclusions: ['1.2.3','1.3.1','1.8','2.2.2','2.2.7','2.2.10','2.2.12','2.3.5','3.4.1','3.4.2','3.4.3','3.4.4','3.4.5','5.2.8','5.3.2','5.4.4']
  # 2.2.2  - Removing X11 packages removes IPA server as dependency !!
  # 2.2.7  - rpcbind/nfs-utils required in IPA server
  # 2.2.10 - Messes with IPA httpd config
  # 2.2.12 - samba part of IPA server install
  # 2.3.5  - don't remove LDAP components from IPA server
  # 5.4.4  - don't mess with umasks on IPA server
cis_chrony_servers: |+
  server ntp1.core.home.gatwards.org iburst
  server 0.centos.pool.ntp.org iburst
cis_skip_lock_users:
- root
- halt
- shutdown
- sync
- named
- dirsrv
