---
# defaults file for ansible-role-adsb

# User/Group to run processes as
adsb_owner: adsb
adsb_group: adsb

# Home Location
adsb_lat: '12.345'
adsb_lon: '123.456'

# Mode-S Mixer defaults
adsb_modesmixer_tarball: modesmixer2_rpi2-3_deb9_20190413.tgz
adsb_modesmixer__inConnect: []
adsb_modesmixer__inConnectId: []
adsb_modesmixer__inServer: []
adsb_modesmixer__inServerId: []
adsb_modesmixer__inServerUdp: []
adsb_modesmixer__inSerial: []
adsb_modesmixer__outConnect: []
adsb_modesmixer__outConnectId: []
adsb_modesmixer__outConnectUdp: []
adsb_modesmixer__outServer: []
adsb_modesmixer__globes:
adsb_modesmixer__web: '8081'
adsb_modesmixer__google_key:
adsb_modesmixer__web_auth:
adsb_modesmixer__disable_web_log: False
#adsb_modesmixer__silhouettes: "{{ adsb_local_db_base }}/silhouettes"
#adsb_modesmixer__pictures: "{{ adsb_local_db_base }}/pictures"
#adsb_modesmixer__db: "{{ adsb_local_db_base }}/db"
adsb_modesmixer__keep: False
#adsb_modesmixer__frdb: "{{ adsb_local_db_base }}/db"
adsb_modesmixer__location: "{{ adsb_lat }}:{{ adsb_lon }}"
adsb_modesmixer__add_reference_point:
adsb_modesmixer__add_points:
adsb_modesmixer__localtime: True
adsb_modesmixer__filter_expire:
adsb_modesmixer__valid_adsb:
adsb_modesmixer__valid_modes:
adsb_modesmixer__filter_nocountry: False
adsb_modesmixer__filter_dup:
adsb_modesmixer__flight_expire_time:
adsb_modesmixer__log_noconsole: True
adsb_modesmixer__log_file: /var/log/modesmixer2.log
adsb_modesmixer__log_level: '4'
adsb_modesmixer__metric: False


# PiAware / FlightAware defaults:
adsb_flightaware_username:
adsb_flightaware_password: 'ChangeMe'
adsb_flightaware_feedid: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
adsb_flightaware_receiver_type: relay
adsb_flightaware_receiver_address: localhost

# FlightRadar24
adsb_fr24feed_key: 'xxxxxxxxxxx'
adsb_fr24feed_receiver: beast-tcp
adsb_fr24feed_receiver_address: '127.0.0.1'
adsb_fr24feed_raw_output: 'no'        # Enable RAW data feed on port 30334
adsb_fr24feed_bs_output: 'no'         # Enable Basestation data feed on port 30003

# Dump1090 defaults
adsb_dump1090_enabled: 'yes'
adsb_dump1090_rec_index: '0'
adsb_dump1090_rec_gain: '-10'
adsb_dump1090_rec_ppm: '0'
adsb_dump1090_decoder_maxrange: '360'
adsb_dump1090_decoder_fix: true
adsb_dump1090_decoder_modeac: true                # Enable decoding of SSR Modes 3/A & 3/C
adsb_dump1090_decoder_forward_mlat: true          # Allow forwarding of received mlat results to output ports
adsb_dump1090_lat: "{{ adsb_lat }}"
adsb_dump1090_lon: "{{ adsb_lon }}"
adsb_dump1090_net: true                   # Enable networking
adsb_dump1090_net_only: false             # Enable just networking, no RTL device or file used
adsb_dump1090_net_heartbeat: 60           # TCP heartbeat rate in seconds
adsb_dump1090_net_ro_interval: '0.2'      # TCP output memory flush rate in seconds
adsb_dump1090_net_ro_size: '1300'         # TCP output minimum size
adsb_dump1090_net_bind_ip: '0.0.0.0'      # IP address to bind to (default: Any; Use 127.0.0.1 for private)
adsb_dump1090_net_ri_port: '0'            # Raw input port
adsb_dump1090_net_ro_port: '30002'        # Raw output port
adsb_dump1090_net_sbs_port: '30003'       # Basestation format output port
adsb_dump1090_net_bi_port: '30004,30104'  # Beast format input port
adsb_dump1090_net_bo_port: '30005'        # Beast format output port
adsb_dump1090_json_location_accuracy: 1
adsb_dump1090_json_path:
adsb_dump1090_json_interval: 1

# VirtualRadarServer defaults
adsb_vrs_user: vrs
adsb_vrs_group: vrs
adsb_vrs_base: /opt/VRS
adsb_vrs_web_port: '8080'
adsb_vrs_admin_user: admin
adsb_vrs_admin_pass: 'ChangeMe'
