
- name: Deploy local node_exporter configuration
  template:
    src: "local_exporter.yml.j2"
    dest: "{{ docker_persistent_store_root }}/config/nodeexporter/local_http_targets.yml"

- name: Deploy HTTP node_exporter target configurations
  template:
    src: "exporter_targets.yml.j2"
    dest: "{{ docker_persistent_store_root }}/config/nodeexporter/{{ item.project }}_http_targets.yml"
  with_items: "{{ prometheus_node_exporter_targets }}"
  when: prometheus_node_exporter_targets is defined and prometheus_node_exporter_targets|length > 0

- name: Deploy TLS node_exporter target configurations
  template:
    src: "exporter_targets.yml.j2"
    dest: "{{ docker_persistent_store_root }}/config/nodeexporter/{{ item.project }}_tls_targets.yml"
  with_items: "{{ prometheus_node_exporter_tls_targets }}"
  when: prometheus_node_exporter_tls_targets is defined and prometheus_node_exporter_tls_targets|length > 0

- name: Deploy vdsm_exporter target configurations
  template:
    src: "exporter_targets.yml.j2"
    dest: "{{ docker_persistent_store_root }}/config/exporters/{{ item.project }}_vdsm_targets.yml"
  with_items: "{{ prometheus_vdsm_exporter_targets }}"
  when: prometheus_vdsm_exporter_targets is defined and prometheus_vdsm_exporter_targets|length > 0
