---
- name: Provision InfluxDB container
  remote_user: svc-ansible
  become: true
  hosts: docker_nas
  vars_files:
  - vault.yml

  tasks:
  - name: Ensure InfluxDB config paths exist
    tags:
    - influxdb
    - docker
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - /volume2/docker/influxdb/config
    - /volume2/docker/influxdb/data

  - name: Deploy InfluxDB configuration
    tags:
    - influxdb
    - docker
    template:
      src: influxdb.conf.j2
      dest: /volume2/docker/influxdb/config/influxdb.conf
      owner: root
      group: root
      mode: 0644
    register: influxdb_config

  - name: Deploy InfluxDB container
    tags:
    - influxdb
    - docker
    include_tasks: tasks/deploy_container.yml
    vars:
      name: influxdb
      image: influxdb
      # restart_policy: unless-stopped
      published_ports:
      - '8086:8086'
      volumes:
      - /volume2/docker/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /volume2/docker/influxdb/data:/var/lib/influxdb

  - name: Restart InfluxDB container
    tags:
    - influxdb
    - docker
    docker_container:
      name: influxdb
      state: restart
    when: influxdb_config.changed


- name: Configure InfluxDB
  remote_user: svc-ansible
  become: true
  hosts: docker_nas

  tasks:
  - name: Install prerequisites
    tags:
    - influxdb
    pip:
      name: influxdb
      state: present

  - name: Create Databases
    tags:
    - influxdb
    influxdb_database:
      database_name: "{{ item.name }}"
      hostname: influxdb.core.home.gatwards.org
    with_items: "{{ hostvars[groups['influxdb'][0]].influxdb_databases }}"

  - name: Configure retention policies
    tags:
    - influxdb
    influxdb_retention_policy:
      database_name: "{{ item.name }}"
      hostname: influxdb.core.home.gatwards.org
      duration: "{{ item.retention_policy.duration }}"
      policy_name: "{{ item.retention_policy.name }}"
      replication: 1
    with_items: "{{ hostvars[groups['influxdb'][0]].influxdb_databases }}"
