---
- name: Install Prometheus
  remote_user: svc-ansible
  become: true
  hosts: docker_nas
  vars_files:
  - vault.yml

  tasks:
  - name: Deploy Prometheus container
    tags:
    - monitoring
    - prometheus
    - docker
    import_role:
      name: ansible-role-docker-monitoring
    vars:
      docker_persistent_store_root: /volume2/docker/prometheus
      docker_ext_prometheus_port: '9990'
      prometheus_config_global_external_labels:
        prom_cluster: CORE
      prometheus_config_alerting:
        alertmanagers:
        - static_configs:
          - targets:
            - alertmanager.core.home.gatwards.org:9093
      prometheus_node_exporter_targets:
      - project: HOME
        targets:
        - openhab.core.home.gatwards.org:9100
        - rpi-util1.core.home.gatwards.org:9100
        - rpi-util2.core.home.gatwards.org:9100
        - foreman.core.home.gatwards.org:9100
        - kvm1.core.home.gatwards.org:9100
        - ipa1.ipa.home.gatwards.org:9100
        - ipa2.ipa.home.gatwards.org:9100
      - project: LAB
        targets:
        - baremetal1.lab.home.gatwards.org:9100
      # prometheus_node_exporter_tls_targets:
      # - project: HOME
      #   targets:
      #   - test1.core.home.gatwards.org:9100
      # - project: LAB
      #   targets:
      #   - test1.lab.home.gatwards.org:9100
      prometheus_config_scrape_configs:
      - job_name: 'prometheus'
        honor_labels: true
        scrape_interval: '20s'
        scrape_timeout: '2s'
        scheme: 'http'
        static_configs:
        - targets:
          - '{{ inventory_hostname }}:9990'
      - job_name: 'alertmanager'
        honor_labels: true
        scrape_interval: '20s'
        scrape_timeout: '2s'
        scheme: 'http'
        static_configs:
        - targets:
          - '{{ inventory_hostname }}:9093'
      - job_name: 'grafana'
        honor_labels: true
        scrape_interval: '20s'
        scrape_timeout: '2s'
        scheme: 'http'
        static_configs:
        - targets:
          - 'grafana.core.home.gatwards.org:3000'
      - job_name: 'node_exporter'
        honor_labels: true
        scheme: 'http'
        file_sd_configs:
        - files:
          - "/etc/prometheus/nodeexporter/*_http_targets.yml"
      - job_name: 'tls_node_exporter'
        honor_labels: true
        scheme: 'https'
        file_sd_configs:
        - files:
          - "/etc/prometheus/nodeexporter/*_tls_targets.yml"