---
- name: oVirt Host
  remote_user: svc-ansible
  become: true
  hosts: ovirt

  tasks:
  - name: Check correct OS version
    assert:
      that:
      - ("{{ ansible_distribution }} == RedHat") or ("{{ ansible_distribution }} == CentOS")
      - "{{ ansible_distribution_major_version }} == 7"
      fail_msg: "Incompatible OS version detected"

  - name: Install oVirt repos
    yum:
      name: https://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm
      state: present

  - name: Install oVirt cockpit dashboard
    yum:
      name: cockpit-ovirt-dashboard
      state: present

  - name: Enable cockpit firewall ports
    firewalld:
      service: cockpit
      immediate: yes
      permanent: yes
      state: enabled

  - name: Enable cockpit
    systemd:
      name: cockpit.socket
      state: started
