---
- name: oVirt Host
  remote_user: svc-ansible
  become: true
  hosts: ovirt

  tasks:
  - name: Check correct OS version
    assert:
      that:
      - ("{{ ansible_distribution }} == RedHat") or ("{{ ansible_distribution }} == CentOS")
      - "{{ ansible_distribution_major_version }} == 7"
      fail_msg: "Incompatible OS version detected"

  - name: Install oVirt repos
    yum:
      name: https://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm
      state: present

  - name: Install oVirt cockpit dashboard
    yum:
      name: cockpit-ovirt-dashboard
      state: present

  - name: Enable cockpit firewall ports
    firewalld:
      service: cockpit
      immediate: yes
      permanent: yes
      state: enabled

  - name: Enable cockpit
    systemd:
      name: cockpit.socket
      state: started

  # Now we need to bootstrap oVirt via cockpit http  :-(
  - name: Notify user
    debug:
      msg: "Please login to cockpit at https://{{ ansible_fqdn }}:9090 to complete the oVirt installation"


# yum install ovirt-hosted-engine-setup

# hosted-engine --deploy


###############################################################################
# Add prometheus exporter
- name: oVirt VDSM Prometheus exporter
  remote_user: svc-ansible
  become: true
  hosts: ovirt

  tasks:
  - name: Install vdsm-prometheus repo
    tags:
    - monitoring
    - vdsm_exporter
    copy:
      content: |
        [copr:copr.fedorainfracloud.org:rfenkhuber:vdsm-prometheus]
        name=Copr repo for vdsm-prometheus owned by rfenkhuber
        baseurl=https://download.copr.fedorainfracloud.org/results/rfenkhuber/vdsm-prometheus/epel-7-$basearch/
        type=rpm-md
        skip_if_unavailable=True
        gpgcheck=1
        gpgkey=https://download.copr.fedorainfracloud.org/results/rfenkhuber/vdsm-prometheus/pubkey.gpg
        repo_gpgcheck=0
        enabled=1
        enabled_metadata=1
      dest: /etc/yum.repos.d/vdsm-prometheus.repo
      owner: root
      group: root
      mode: '0644'

  - name: Install vdsm-prometheus
    tags:
    - monitoring
    - vdsm_exporter
    yum:
      name: vdsm-prometheus
      state: present

  - name: Disable prometheus client-TLS requirement
    tags:
    - monitoring
    - vdsm_exporter
    copy:
      content: |
        [Service]
        Environment=VDSM_PROM_OPTS=-no-prom-auth
      dest: /etc/systemd/system/vdsm-prometheus.service.d/10-vdsm-prometheus.conf
      owner: root
      group: root
      mode: '0644'

  - name: Start vdsm-prometheus service
    tags:
    - monitoring
    - vdsm_exporter
    service:
      name: vdsm-prometheus
      state: started
      enabled: true

  - name: Open vdsm-prometheus firewall port
    tags:
    - monitoring
    - vdsm_exporter
    firewalld:
      port: '8181/tcp'
      immediate: yes
      permanent: yes
      state: enabled

