---
- name: Install Weather Server
  remote_user: svc-ansible
  become: true
  hosts: docker_nas
  vars_files:
  - vault.yml

  tasks:
  - name: Deploy Weewx container
    tags:
    - weather
    - docker
    import_role:
      name: ansible-role-docker-weewx
    vars:
      docker_persistent_store_root: /volume2/docker/weewx
      weewx_version: 3.9.2
      #weewx_version: latest   # Latest takes us to v4.4 which breaks MQTT
      weewx_location: Bungendore, NSW
      weewx_latitude: "{{ latitude }}"
      weewx_longitude: "{{ longitude }}"
      weewx_altitude: 2300
      weewx_vantage_iss_id: 4
      weewx_vantage_url: weatherlink.core.home.gatwards.org
      weewx_vantage_tcp_port: 22222
      weewx_cwop_enable: 'true'
      weewx_cwop_station: VK2XJG
      weewx_cwop_passcode: "{{ vault_weewx_cwop_passcode }}"
      weewx_wunderground_enable: 'true'
      weewx_wunderground_station: INEWSOUT867
      weewx_wunderground_password: "{{ vault_weewx_wunderground_password }}"
      weewx_wunderground_rapidfire: 'True'
      weewx_use_mqtt: true
      weewx_mqtt_url: "mqtt://{{ mqtt_broker_fqdn }}:1883/"
      weewx_web_mount: /volume1/web/weewx

  - name: Wait for container
    wait_for:
      timeout: 10

  - name: Check if MQTT plugin is installed
    command: /usr/local/bin/docker exec weewx bash -c '/home/weewx/bin/wee_extension --list'
    register: extensions
    changed_when: false

  - block:
      # Latest container uses pip3 but fails to install prereqs for python-cjson
    - name: Install pip pre-reqs for MQTT plugin
      command: /usr/local/bin/docker exec weewx bash -c 'pip install paho-mqtt python-cjson'
      #command: /usr/local/bin/docker exec weewx bash -c 'pip3 install paho-mqtt'

    - name: Download MQTT plugin
      command: /usr/local/bin/docker exec weewx bash -c 'curl -o weewx-mqtt-0.19.tgz http://lancet.mit.edu/mwall/projects/weather/releases/weewx-mqtt-0.19.tgz'

    - name: Install MQTT plugin
      command: /usr/local/bin/docker exec weewx bash -c '/home/weewx/bin/wee_extension --install weewx-mqtt-0.19.tgz'
      ignore_errors: true
      register: ext_installed
    when: '"mqtt" not in extensions.stdout'

  - name: Restart container
    docker_container:
      name: weewx
      state: started
      restart: true
    when: ext_installed.changed

# # TODO:
# # /var/www/html/stormvue for TS tracking (TAR bundle from Boltek)
# # Requires also vsftpd with stormvue user
