---
# tasks file for docker-prometheus

## Won't install on Synology NAS
# - name: Install prerequisites
#   pip:
#     name: docker-compose
#     state: present

- include_tasks: deploy_containers.yml
- include_tasks: scrape_targets.yml
