---
# Postgresql
openhab_db_user: openhab2
openhab_db_password: 'ChangeMe'
openhab_db_name: openhab2
openhab_db_host: 127.0.0.1
postgresql_pgdata: /var/lib/pgsql/data

influxdb_openhab_password: 'ChangeMe'

# MQTT Defaults
mqtt_broker_fqdn: localhost
mqtt_broker_port: '1883'

# OpenHAB configuration defaults
openhab_package: standard
openhab_remote_addons_enabled: true

openhab_audio_sink: ''

openhab_bindings:
  - network
  - ntp

openhab_ui:
  - basic
  - paper
  - habmin
  - habpanel
  - homebuilder

openhab_action: []

openhab_persistence:
  - jdbc-postgresql
  - rrd4j

openhab_transformation:
  - javascript
  - map
  - regex

openhab_voice: []

openhab_misc: []
