---
# tasks file for role-openhab

- name: Source OS family vars
  include_vars: "{{ ansible_distribution_file_variety }}.yml"

- name: Installation
  tags:
  - openhab
  include_tasks: install.yml

- name: Configure OpenHab
  tags:
  - openhab
  - config
  include_tasks: openhab_config.yml
