---
# handlers file for ansible-role-extra-hardening
- name: restart_firewalld
  service:
    name: firewalld
    state: restarted

- name: restart_rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
