---
# tasks file for ansible-freeipa-client

- name: Import variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set DNS server
  become: true
  when: ipaclient_dns_server is defined
  lineinfile:
    state: present
    line: "nameserver {{ ipaclient_dns_server }}"
    dest: /etc/resolv.conf

- name: Install required packages
  become: true
  with_items: "{{ ipaclient_packages }}"
  package:
    state: present
    name: "{{ item }}"

- name: Check if host is enrolled
  register: ipaclient_ipaconf
  check_mode: no
  stat:
    path: /etc/ipa/default.conf

- block:
  - name: Attempt to enroll host in domain
    become: true
    command: >
      {{ ipaclient_install_command }}
      {{'--hostname=' + ipaclient_hostname  if ipaclient_hostname is defined else ''}}
      {% for freeipa_server in ipaclient_servers %}
      --server={{ freeipa_server }}
      {% endfor %}
      --domain={{ ipaclient_domain }}
      --principal={{ ipaclient_enroll_user }}
      --password={{ ipaclient_enroll_pass }}
      --ssh-trust-dns
      {{ '--mkhomedir' if ipaclient_mkhomedir else ''}}
      {{ '--enable-dns-updates' if ipaclient_enable_dns_updates else ''}}
      --unattended
      {{ '--all-ip-addresses' if ipaclient_all_ip_addresses else ''}}
      {{ '--ip-address=' + ipaclient_ip_address if ipaclient_ip_address else ''}}
      {{ '--no-ntp' if not ipaclient_enable_ntp else ''}}
      {{ '--force-join' if ipaclient_force_join else ''}}
    register: ipajoin
    ignore_errors: true

  - name: Attempt to force enroll host in domain
    become: true
    command: >
      {{ ipaclient_install_command }}
      {{'--hostname=' + ipaclient_hostname  if ipaclient_hostname is defined else ''}}
      {% for freeipa_server in ipaclient_servers %}
      --server={{ freeipa_server }}
      {% endfor %}
      --domain={{ ipaclient_domain }}
      --principal={{ ipaclient_enroll_user }}
      --password={{ ipaclient_enroll_pass }}
      --ssh-trust-dns
      {{ '--mkhomedir' if ipaclient_mkhomedir else ''}}
      {{ '--enable-dns-updates' if ipaclient_enable_dns_updates else ''}}
      --unattended
      {{ '--all-ip-addresses' if ipaclient_all_ip_addresses else ''}}
      {{ '--ip-address=' + ipaclient_ip_address if ipaclient_ip_address else ''}}
      {{ '--no-ntp' if not ipaclient_enable_ntp else ''}}
      --force-join
    when: ipajoin.failed
  when: ipaclient_force_join or not ipaclient_ipaconf.stat.exists


- name: Configure sssd username format
  when: ipaclient_sssd_shortnames|bool
  ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/{{ ipaclient_domain }}
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: override_homedir
    value: "/home/%u"
  - option: full_name_format
    value: "%1$s"
  notify: Restart sssd
