---
# tasks file for ansible-role-ipaclient

- name: Assert required variables
  assert:
    that:
      - ipaclient_servers is defined
      - ipaclient_domain is defined
      - ipaclient_enroll_user is defined
      - ipaclient_enroll_pass is defined

# Enroll client system
- include_tasks: enroll_client.yml

- include_tasks: krb5.yml

# Request, sign and deploy server certs
- include_tasks: get_ssl_certs.yml
  when: ipaclient_ssl_create_certs|bool
