---
# handlers file for docker-prometheus
- name: restart_prometheus_container
  docker_container:
    name: prometheus
    state: started
    restart: true

- name: restart_grafana_container
  docker_container:
    name: grafana
    state: started
    restart: true
