---

- name: Install piaware repo
  apt:
    deb: https://flightaware.com/adsb/piaware/files/packages/pool/piaware/p/piaware-support/piaware-repository_3.8.0_all.deb
    update_cache: true

- name: Install Dump1090
  package:
    name: dump1090-fa
    state: present

#- name: Configure dump1090
#  /etc/default/dump1090-fa

# --net
# --net-only
# --forward-mlat
