---
# - name: Install piaware repo
#   apt:
#     deb: https://flightaware.com/adsb/piaware/files/packages/pool/piaware/p/piaware-support/piaware-repository_3.8.0_all.deb
#     update_cache: true

- name: Install PiAware repo
  apt_repository:
    repo: 'deb http://flightaware.com/adsb/piaware/files/packages buster piaware'
    update_cache: true

- name: Install Dump1090
  package:
    name: dump1090-fa
    state: present

- name: Configure dump1090
  template:
    src: dump1090-fa.j2
    dest: /etc/default/dump1090-fa
  notify: restart dump1090

- name: Open firewall ports
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
  - "80/tcp"
  - "8080/tcp"

- name: Enable dump1090-fa
  systemd:
    name: dump1090-fa
    state: started
    enabled: true
