---
# tasks file for ansible-role-adsb



# - name: Configure Mode-S Mixer
#   include_tasks: modesmixer.yml

# - name: Configure Dump1090
#   include_tasks: dump1090.yml

# - name: Configure FlightRadar24 Feeder
#   include_tasks: fr24feed.yml

# - name: Configure FlightAware Feeder
#   include_tasks: piaware.yml

- name: Configure Virtual Radar Server
  include_tasks: vrs.yml
