---
# tasks file for ansible-role-adsb

- name: Create ADSB user
  user:
    name: "{{ adsb_owner }}"
    state: present

- name: Set group write permission on ADSB directory
  file:
    path: "/home/{{ adsb_owner }}"
    mode: '0775'

- name: Add users to ADSB group
  user:
    name: "{{ item }}"
    state: present
    groups: adsb
    append: true
  with_items: "{{ adsb_group_members }}"
  when: adsb_group_members is defined and adsb_group_members|length > 0

- name: Create directories
  file:
    path: "/home/{{ adsb_owner }}/{{ item }}"
    state: directory
    owner: "{{ adsb_owner }}"
    group: "{{ adsb_owner }}"
    mode: '0755'
  with_items:
  - flags
  - silhouettes

- name: Check if BaseStation.sqb exists
  stat:
    path: "/home/{{ adsb_owner }}/BaseStation.sqb"
  register: sqb

- name: Resore initial BaseStation.sqb
  get_url:
    url: http://webshare.lab.home.gatwards.org/ADSB/BaseStation.sqb
    dest: "/home/{{ adsb_owner }}/BaseStation.sqb"
    owner: "{{ adsb_owner }}"
    group: "{{ adsb_owner }}"
    mode: '0664'
  when: not sqb.stat.exists

- name: Extract Operator Flags
  unarchive:
    src: http://webshare.lab.home.gatwards.org/ADSB/OperatorFlags.zip
    dest: "/home/{{ adsb_owner }}/flags"
    remote_src: true
    owner: "{{ adsb_owner }}"
    group: "{{ adsb_owner }}"
    mode: '0644'

- name: Extract Silhouettes
  unarchive:
    src: http://webshare.lab.home.gatwards.org/ADSB/Silhouettes.zip
    dest: "/home/{{ adsb_owner }}/silhouettes"
    remote_src: true
    owner: "{{ adsb_owner }}"
    group: "{{ adsb_owner }}"
    mode: '0644'


- name: Configure Mode-S Mixer
  include_tasks: modesmixer.yml

- name: Configure Dump1090
  include_tasks: dump1090.yml

- name: Configure FlightRadar24 Feeder
  include_tasks: fr24feed.yml

- name: Configure FlightAware Feeder
  include_tasks: piaware.yml

- name: Configure Virtual Radar Server
  include_tasks: vrs.yml

- name: Install SQLiteBrowser
  package:
    name: sqlitebrowser
    state: present
