---
- name: Read vars
  include_vars: modesmixer.yml

- name: Create ADSB user
  user:
    name: "{{ adsb_owner }}"
    state: present

- name: Extract package
  unarchive:
    src: "{{ adsb_modesmixer_tarball }}"
    dest: /usr/local/bin
    creates: /usr/local/bin/modesmixer2

- name: Install Mode-S mixer systemd service
  template:
    src: modesmixer2.service.j2
    dest: /etc/systemd/system/modesmixer2.service
  notify:
    - reload daemon
    - restart modesmixer2

- name: Enable Mode-S mixer
  systemd:
    name: modesmixer2
    state: started
    enabled: true

- name: Open firewall ports
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
  - "{{ adsb_modesmixer__web }}/tcp"
