---
# defaults file for docker-prometheus

docker_persistent_store_root: /volume2/docker/prometheus
docker_restart_policy: unless-stopped
docker_ext_prometheus_port: '9090'
docker_ext_alertmanager_port: '9093'
docker_ext_nodeexporter_port: '9100'

prometheus_config_global_scrape_interval: '15s'
prometheus_config_global_evaluation_interval: '15s'
prometheus_config_global_scrape_timeout: '10s'
prometheus_config_global_external_labels: []

# Allow Prometheus to discover alert managers
prometheus_config_alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

prometheus_config_rule_files:
  - "/etc/prometheus/rules/*.rules.yml"

prometheus_config_scrape_configs:
- job_name: 'prometheus'
  honor_labels: true
  scrape_interval: '20s'
  scrape_timeout: '2s'
  metrics_path: '/metrics'
  scheme: 'http'
  static_configs:
  - targets:
    - '{{ ansible_fqdn }}:9090'
- job_name: 'node_exporter'
  honor_labels: true
  scheme: 'http'
  file_sd_configs:
  - files:
    - "/etc/prometheus/nodeexporter/*_http_targets.yml"
- job_name: 'tls_node_exporter'
  honor_labels: true
  scheme: 'https'
  file_sd_configs:
  - files:
    - "/etc/prometheus/nodeexporter/*_tls_targets.yml"

prometheus_node_exporter_targets: []
# - project: HOME
#   targets:
#   - openhab.core.home.gatwards.org:9100
#   - rpi-util1.core.home.gatwards.org:9100
prometheus_node_exporter_tls_targets: []
# - project: HOME
#   targets:
#   - openhab.core.home.gatwards.org:9100
#   - rpi-util1.core.home.gatwards.org:9100