---
# tasks file for ansible-role-extra-hardening

# BREAKS FIREWALLD ON RPI !!
- name: Configure default DROP logging in firewalld
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^LogDenied'
    line: 'LogDenied=unicast'
    state: present
    backrefs: yes
  notify: restart_firewalld
  when: ansible_distribution != 'Debian'

- name: Redirect firewall logs
  copy:
    content: |
      :msg,contains,"_DROP" /var/log/iptables.log
      :msg,contains,"_REJECT" /var/log/iptables.log
      :msg,contains,"ACCEPT: " /var/log/iptables.log
      & stop
    dest: /etc/rsyslog.d/iptables.conf
  notify: restart_rsyslog

- name: Add firewall logrotate
  copy:
    content: |
      /var/log/iptables.log {
        nocreate
        daily
        missingok
        rotate 7
        compress
      }
    dest: /etc/logrotate.d/iptables

- name: Add logging SSH to firewall
  firewalld:
    immediate: true
    permanent: true
    state: enabled
    rich_rule: 'rule service name="ssh" log prefix="ACCEPT: " accept'

- name: Remove default ssh service from firewall
  firewalld:
    immediate: true
    permanent: true
    state: disabled
    service: ssh

- name: Remove dhcpv6 service from firewall
  firewalld:
    service: dhcpv6-client
    state: disabled
    permanent: true
    immediate: true

- name: Set FQDN on syslog messages
  copy:
    content: |
      $PreserveFQDN on
    dest: /etc/rsyslog.d/preserve_fqdn.conf
    owner: root
    group: root
    mode: '0600'

- name: Include RaspberryPi tasks
  include_tasks: raspberry.yml
  when: ansible_distribution == 'Debian'
