---

- name: Set Issue banner
  template:
    src: issue.j2
    dest: "{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
  - /etc/issue
  - /etc/issue.net

- name: Remove local users
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - ftp
    - operator
    - games
  ignore_errors: true

- name: SSH Server hardening
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
  notify: restart sshd

- name: Login defaults - Max Days
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS\s+'
    line: 'PASS_MAX_DAYS\t90'
    state: present
    backrefs: yes

- name: Login defaults - Min Days
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS\s+'
    line: 'PASS_MIN_DAYS\t1'
    state: present
    backrefs: yes

# TODO: Fix to work with '#PASS_MIN_LEN' in RPi - PAM
- name: Login defaults - Min Length
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_LEN\s+'
    line: 'PASS_MIN_LEN\t11'
    state: present
    backrefs: yes

- name: Login defaults - Warn Days
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE\s+'
    line: 'PASS_WARN_AGE\t14'
    state: present
    backrefs: yes

# TODO: Fix to work with '# INACTIVE=-1' in RPi
# - name: Login defaults - Inactive Account Expiry
#   lineinfile:
#     path: /etc/default/useradd
#     regexp: '^INACTIVE'
#     line: 'INACTIVE=35'
#     state: present
#     backrefs: yes
